require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FlightRoutesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FlightRoute. As you add validations to FlightRoute, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { origin: "DCA", destination: "LAX", food: true }
  }

  let(:invalid_attributes) {
    { origin: "Q", destination: "LAX", food: true }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FlightRoutesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all flight_routes as @flight_routes" do
      flight_route = FlightRoute.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:flight_routes)).to eq([flight_route])
    end
  end

  describe "GET #show" do
    it "assigns the requested flight_route as @flight_route" do
      flight_route = FlightRoute.create! valid_attributes
      get :show, params: {id: flight_route.to_param}, session: valid_session
      expect(assigns(:flight_route)).to eq(flight_route)
    end
  end

  describe "GET #new" do
    it "assigns a new flight_route as @flight_route" do
      get :new, params: {}, session: valid_session
      expect(assigns(:flight_route)).to be_a_new(FlightRoute)
    end
  end

  describe "GET #edit" do
    it "assigns the requested flight_route as @flight_route" do
      flight_route = FlightRoute.create! valid_attributes
      get :edit, params: {id: flight_route.to_param}, session: valid_session
      expect(assigns(:flight_route)).to eq(flight_route)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FlightRoute" do
        expect {
          post :create, params: {flight_route: valid_attributes}, session: valid_session
        }.to change(FlightRoute, :count).by(1)
      end

      it "assigns a newly created flight_route as @flight_route" do
        post :create, params: {flight_route: valid_attributes}, session: valid_session
        expect(assigns(:flight_route)).to be_a(FlightRoute)
        expect(assigns(:flight_route)).to be_persisted
      end

      it "redirects to the created flight_route" do
        post :create, params: {flight_route: valid_attributes}, session: valid_session
        expect(response).to redirect_to(FlightRoute.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved flight_route as @flight_route" do
        post :create, params: {flight_route: invalid_attributes}, session: valid_session
        expect(assigns(:flight_route)).to be_a_new(FlightRoute)
      end

      it "re-renders the 'new' template" do
        post :create, params: {flight_route: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { destination: "ORD" }
      }

      it "updates the requested flight_route" do
        flight_route = FlightRoute.create! valid_attributes
        put :update, params: {id: flight_route.to_param, flight_route: new_attributes}, session: valid_session
        flight_route.reload
        expect(flight_route.destination).to eq "ORD"
      end

      it "assigns the requested flight_route as @flight_route" do
        flight_route = FlightRoute.create! valid_attributes
        put :update, params: {id: flight_route.to_param, flight_route: valid_attributes}, session: valid_session
        expect(assigns(:flight_route)).to eq(flight_route)
      end

      it "redirects to the flight_route" do
        flight_route = FlightRoute.create! valid_attributes
        put :update, params: {id: flight_route.to_param, flight_route: valid_attributes}, session: valid_session
        expect(response).to redirect_to(flight_route)
      end
    end

    context "with invalid params" do
      it "assigns the flight_route as @flight_route" do
        flight_route = FlightRoute.create! valid_attributes
        put :update, params: {id: flight_route.to_param, flight_route: invalid_attributes}, session: valid_session
        expect(assigns(:flight_route)).to eq(flight_route)
      end

      it "re-renders the 'edit' template" do
        flight_route = FlightRoute.create! valid_attributes
        put :update, params: {id: flight_route.to_param, flight_route: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested flight_route" do
      flight_route = FlightRoute.create! valid_attributes
      expect {
        delete :destroy, params: {id: flight_route.to_param}, session: valid_session
      }.to change(FlightRoute, :count).by(-1)
    end

    it "redirects to the flight_routes list" do
      flight_route = FlightRoute.create! valid_attributes
      delete :destroy, params: {id: flight_route.to_param}, session: valid_session
      expect(response).to redirect_to(flight_routes_url)
    end
  end

end
